- name: EC2 Deploy
  hosts: localhost
  connection: local

  tasks:
    - name: Spousteni EC2 instance
      ec2_instance:
        instance_type: t2.medium
        tags:
          Name: "prod"
          Created: "{{ ansible_date_time.epoch }}"
        image_id: ami-0230bd60aa48260c6
        region: us-east-1
        key_name: test
        vpc_subnet_id: subnet-083d59eaf87353de9
        count: 1
        network:
          assign_public_ip: yes
        wait: yes
        security_group: eshop
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        security_token: "{{ session_token }}"
      register: ec2_instance_result

    - name: Add instance host to sec group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2_instance_result.instances }}"

    - name: Wait for SSH connection
      delegate_to: "{{ item.public_ip_address }}"
      wait_for_connection:
        delay: 30
        timeout: 300
      loop: "{{ ec2_instance_result.instances }}"

- name: Configure EC2
  hosts: launched
  connection: ssh

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: latest
        update_cache: yes
      become: yes

    - service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Start Docker on startup
      shell: systemctl enable docker
      become: yes

    - name: Set rights to docker
      shell: usermod -a -G docker ec2-user
      become: yes

    - name: Get project files from git
      git:
        repo: 'https://github.com/jirkin/DevOps_SP.git'
        dest: ./app

    - name: Build docker with eshop
      shell: cd app && docker build -t myeshop:latest .
      become: yes

    - name: Run docker with eshop
      shell: docker run -p 80:3000 myeshop
      async: 45
      poll: 0
      become: yes

    - wait_for:
        port:
          80

- name: Terminate Instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Find by Tag
      ec2_instance_info:
        filters:
          "tag:Name": "prod"
          "instance-state-name": "running"
        region: us-east-1
      register: all_instances

    - name: List & Sort Instances 
      set_fact:
        instances_list: "{{ all_instances.instances | sort(attribute='launch_time', reverse=true) | map(attribute='instance_id') | list }}"
      when: all_instances.instances | length > 0

    - name: Exclude new Instance
      set_fact:
        instances_to_terminate: "{{ instances_to_terminate + [item] }}"
      loop: "{{ instances_list[1:] }}"
      vars:
        instances_to_terminate: []
      when: instances_list | length > 0

    - name: Terminate previous Instances
      ec2_instance:
        state: 'absent'
        instance_ids: "{{ instances_to_terminate }}"
        region: us-east-1
      when: instances_to_terminate | length > 0

    - name: Debug - List Instances to Terminate
      debug:
        var: instances_to_terminate
